project_id = "yzvcpfcmfutczrlporjp"

[functions.check-subscription]
verify_jwt = true

[functions.extract-menu-from-image]
verify_jwt = true

[functions.cielo-payment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.emit-nfce]
verify_jwt = true

[functions.generate-menu-design]
verify_jwt = true

[functions.mercadopago-payment]
verify_jwt = true

[functions.nubank-payment]
verify_jwt = true

[functions.pagseguro-payment]
verify_jwt = true

[functions.pagseguro-webhook]
verify_jwt = false

[functions.rede-payment]
verify_jwt = true

[functions.stone-payment]
verify_jwt = true

[functions.whatsapp-create-device]
verify_jwt = true

[functions.whatsapp-notify-order]
verify_jwt = true

[functions.whatsapp-save-message]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-send-mass]
verify_jwt = true

[functions.whatsapp-sync-device]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-process-message]
verify_jwt = false